# Generated by Django 4.0.2 on 2023-07-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='profession',
        ),
    ]
