# Generated by Django 4.0.2 on 2023-07-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0003_user_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='pro_pic',
            field=models.ImageField(default='static/images/default.png', upload_to='images/'),
        ),
    ]
