# Generated by Django 4.0.2 on 2023-07-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0004_user_registration_pro_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='pro_pic',
        ),
        migrations.CreateModel(
            name='Profile_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(max_length=20)),
                ('secondnumber', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pro_pic', models.ImageField(default='static/images/default.png', upload_to='images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NadaliyaApp.user_registration')),
            ],
        ),
    ]
