# Generated by Django 4.2 on 2023-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0006_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='images/banner')),
            ],
        ),
        migrations.DeleteModel(
            name='ads',
        ),
    ]
