# Generated by Django 4.2 on 2023-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0007_bannerads_delete_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerads',
            old_name='banner_image',
            new_name='banner_image1',
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_image2',
            field=models.FileField(blank=True, null=True, upload_to='images/banner'),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_image3',
            field=models.FileField(blank=True, null=True, upload_to='images/banner'),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_image4',
            field=models.FileField(blank=True, null=True, upload_to='images/banner'),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_image5',
            field=models.FileField(blank=True, null=True, upload_to='images/banner'),
        ),
    ]
