# Generated by Django 4.2 on 2023-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0008_rename_banner_image_bannerads_banner_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerads',
            name='banner_title1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_title3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_title4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='banner_title5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
