# Generated by Django 4.2 on 2023-07-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0009_bannerads_banner_title1_bannerads_banner_title2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image1', models.FileField(blank=True, null=True, upload_to='images/product')),
            ],
        ),
    ]
